import type { Metadata } from "next";
import { Fraunces } from "next/font/google";
import { Roboto } from "next/font/google";

import "./globals.css";

// Fonts
const fraunces = Fraunces({
  subsets: ["latin"],
  weight: ["100","200","300","400","500","600","700","800","900"],
  variable: "--font-fraunces",
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100","200","300","400","500","600","700","800","900"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Lusmo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="fr" className={`${fraunces.variable} ${roboto.variable}`}>
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
