import type { Metadata } from "next";
import { Merriweather } from "next/font/google";
import { Roboto } from "next/font/google";
import { Poppins } from "next/font/google";
import NavBar from "@/Components/assets/NavBar/HeaderContent";
import Cursor from "@/Components/assets/utils/cursor/Cursor";

import "./globals.css";

// Fonts
const merriweather = Merriweather({
  subsets: ["latin"],
  weight: ["300","400","500","600","700","800","900"],
  variable: "--font-merriweather",
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100","200","300","400","500","600","700","800","900"],
  variable: "--font-roboto",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100","200","300","400","500","600","700","800","900"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Lusmo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="fr" className={`${merriweather.variable} ${roboto.variable} ${poppins.variable}`}>
      <body className="antialiased">
        <Cursor />
        <NavBar />

        {children}
      </body>
    </html>
  );
}
